// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SEimC1_tmNAt_kawnqXb2MosEIZImrw',
    appId: '1:905668922669:web:16627babe34cb3566a17a4',
    messagingSenderId: '905668922669',
    projectId: 'fishcab-ab50d',
    authDomain: 'fishcab-ab50d.firebaseapp.com',
    storageBucket: 'fishcab-ab50d.appspot.com',
    measurementId: 'G-K3XD4RZVGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5juF31ve9wg3EUtIVvF6y40QkyJ3k4M',
    appId: '1:905668922669:android:fb3dd3a7117f0d446a17a4',
    messagingSenderId: '905668922669',
    projectId: 'fishcab-ab50d',
    storageBucket: 'fishcab-ab50d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSCNCcpVIgR2qvhiFwSH6VlAXNAPBPFY',
    appId: '1:905668922669:ios:f1efc2dd4bc72dd56a17a4',
    messagingSenderId: '905668922669',
    projectId: 'fishcab-ab50d',
    storageBucket: 'fishcab-ab50d.appspot.com',
    iosClientId: '905668922669-hm5hb6r1gt8ckeosp90dlim4p1aq0fr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishCab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSCNCcpVIgR2qvhiFwSH6VlAXNAPBPFY',
    appId: '1:905668922669:ios:9332638035dc90126a17a4',
    messagingSenderId: '905668922669',
    projectId: 'fishcab-ab50d',
    storageBucket: 'fishcab-ab50d.appspot.com',
    iosClientId: '905668922669-2a2v7hm8knmflaokcdb5qlec8s2fj3l4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishCab.RunnerTests',
  );
}
